ALIST_HOST: "https://alist.goatv.org" # alist ip:port或alist域名，一般填域名即可
ALIST_WEB: "https://alist.goatv.org" # 你的alist域名
ALIST_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicHdkX3RzIjoxNzEzODYzNTU3LCJleHAiOjE3NTEwNDk5NTksIm5iZiI6MTczNTgyMTk1OSwiaWF0IjoxNzM1ODIxOTU5fQ.nVd-nHgV6LFHrmMP0pXkpCqp_pCPydQZx9lrx1GLMBE" # alist token
TELEGRAM_ADMIN_ID: 1076750810 # 管理员用户id，可通过 https://t.me/getletbot 获取id
TELEGRAM_MEMBER: []  # 允许使用bot的 用户、群组、频道（群组和频道id需要加上-100）可通过 https://t.me/getletbot 获取id。 留空为所有人可用
TELEGRAM_BOT_TOKEN: "6835796358:AAELkoVEQr5mM-ZdYDj8MqTsd_ogu8GpH_8" # bot的api token，从 @BotFather 获取
TELEGRAM_API_ID: "28653083" # api_id、api_hash在 https://my.telegram.org/apps 获取
TELEGRAM_API_HASH: "6e4b99e9f8c7473d8ea1274541279255"
TELEGRAM_CHANNEL_ID: "-1002191239013"
BOT_DOWNLOAD_LOCATION: "/Users/lingbin/Downloads/"
MAXIMUM_LEECH_WORKER: 1
MAXIMUM_SYNC_WORKER: 1
SHOULD_USE_DATETIME_CATEGORY: False
BOT_LOGS_LOCATION: "/Users/lingbin/Downloads/logs/"
REDIS_HOST: "45.63.60.108"
REDIS_PORT: 6379
REDIS_PASSWORD: "redis"
MONGO_HOST: "45.63.60.108"
MONGO_PORT: 27017
MONGO_USERNAME: root
MONGO_PASSWORD: root
MONGO_DATABASE_NAME: bot
SKIP_DUPLICATE_LINK_WITHIN_DAYS: 0
FAILED_TASK_EXPIRE_AFTER_DAYS: 7
MAXIMUM_QUEUE_SIZE: 2000
WRITE_STREAM_CONNECT_TIMEOUT: 10.0
RCLONE_REMOTES: "115"
RCLONE_115_COOKIE: "UID=101224206_R2_1732172964;CID=ff79e9f1876c2c577fc20d2b41eafa58;SEID=da7d1c3cb72660c43aea0f48332baa5f2fc4330cc5a3c939b644e09ae53525a3a2e5173c97336a8dbcea139584084704d3de11e9b10da42ec5cb27e1"
MEGA_AUTHORIZATION_EMAIL: a516285875@163.com
MEGA_AUTHORIZATION_PASSWORD: lingbin0390
BUNKR_DOMAIN: bunkr.si
BOT_PROXY_SCHEMAS: "socks5"
BOT_PROXY_HOST: "127.0.0.1"
BOT_PROXY_PORT: 7890
NODE_ENV: "DEVELOPMENT"
DISK_ALERT_THRESHOLD: 10  # 磁盘剩余空间告警阈值（GB）
DISK_ALERT_ENABLED: true  # 是否启用磁盘监控