from enum import StrEnum


class LeechFileStatus(StrEnum):
    INITIAL = 'INITIAL'
    DOWNLOADING = 'DOWNLOADING'
    DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS'
    DOWNLOAD_FAIL = 'DOWNLOAD_FAIL'
    SKIP_DOWNLOAD = 'SKIP_DOWNLOAD'
    UPLOADING = 'UPLOADING'
    UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
    UPLOAD_FAIL = 'UPLOAD_FAIL'
    SKIP_UPLOAD = 'SKIP_UPLOAD'
