from enum import StrEnum


class StatisticItem(StrEnum):
    NUMBER_OF_DOWNLOAD_TASK = 'NUMBER_OF_DOWNLOAD_TASK'
    NUMBER_OF_UPLOAD_TASK = 'NUMBER_OF_UPLOAD_TASK'
    NUMBER_OF_FAILED_TASK = 'NUMBER_OF_FAILED_TASK'
    NUMBER_OF_COMPLETED_TASK = 'NUMBER_OF_COMPLETED_TASK'
    DOWNLOADING_TASK = 'DOWNLOADING_TASK'
    UPLOADING_TASK = 'UPLOADING_TASK'
    NUMBER_OF_DOWNLOAD_WORKER = 'NUMBER_OF_DOWNLOAD_WORKER'
    NUMBER_OF_UPLOAD_WORKER = 'NUMBER_OF_UPLOAD_WORKER'
    NUMBER_OF_DOWNLOAD_QUEUE = 'NUMBER_OF_DOWNLOAD_QUEUE'
    NUMBER_OF_UPLOAD_QUEUE = 'NUMBER_OF_UPLOAD_QUEUE'
